language: node_js

node_js:
  - "node"
  - "lts/*"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

script:
  - npm run ci:test

after_success:
  - npm run ci:report

notifications:
  email: false
